apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'k6'
        static_configs:
          - targets: ['run-k6-from-configmap-service-1:6565']