apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: {{ .Values.k6.name }}
spec:
  parallelism: {{ .Values.k6.parallelism }}
  arguments: --tag testid={{ .Values.k6.name }}
  script:
    configMap:
      name: {{ .Values.TestRun.name }}
      file: {{ .Values.TestRun.test_script }}
  runner:                                              # <=== HERE
    image: uddeshya307/k6-grafana-image:latest
    env:
      - name: K6_OUT
        value: xk6-influxdb=http://jmeter-influxdb-svc:8086/my_db
      - name: K6_INFLUXDB_INSECURE
        value: "true"